name: Deploy Hugo to VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Important for Hugo themes

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build the site
        run: hugo --minify --gc

      - name: Validate build output
        run: |
          [ -d "public" ] || { echo "Build failed: no public directory"; exit 1; }
          [ -f "public/index.html" ] || { echo "Build failed: no index.html"; exit 1; }

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS || 'github.com' }}

      - name: Deploy to VPS via Rsync
        run: |
          rsync -avz --delete --progress \
          -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
          public/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/agungsukariman.com/
          rm: true  # optional: remove existing files first
