name: Deploy Hugo

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.124.1'

    - name: Build Hugo Site
      run: hugo --minify

    - name: Deploy via rsync
      uses: burnett01/rsync-deployments@v1.1
      with:
        switches: -avz --delete
        path: public/
        remote_path: /home/himehime/agungsukariman.com/
        remote_host: ${{ secrets.VPS_HOST }}
        remote_user: ${{ secrets.VPS_USER }}
        remote_key: ${{ secrets.VPS_KEY }}

