name: Deploy Hugo Site to Biznet VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Fetch Hugo themes
        fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true  # Use Hugo Extended for SCSS/SASS support

    - name: Build Hugo site
      run: hugo --minify

    - name: Setup SSH
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p ~/.ssh
        # Create SSH key file from your existing .pem
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/biznet.pem
        chmod 600 ~/.ssh/biznet.pem
        # Add host to known_hosts to avoid host verification
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      if: github.ref == 'refs/heads/main'
      run: |
        # Deploy new site
        rsync -avz --delete -e "ssh -i ~/.ssh/biznet.pem -o StrictHostKeyChecking=no" \
          ./public/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/agungsukariman.com/

        # Set proper permissions and restart web server
        ssh -i ~/.ssh/biznet.pem -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          sudo chown -R www-data:www-data /var/www/agungsukariman.com
          sudo chmod -R 755 /var/www/agungsukariman.com
          
          # Restart web server (adjust based on your setup)
          if systemctl is-active --quiet nginx; then
            sudo systemctl reload nginx
          elif systemctl is-active --quiet apache2; then
            sudo systemctl reload apache2
          fi
          
          echo "Hugo site deployed successfully!"
        EOF

    - name: Cleanup
      if: always()
      run: |
        rm -f ~/.ssh/biznet.pem
